## ===============================
## Application Info
## ===============================
#spring.application.name=leave-management
#server.port=8080
#
## ===============================
## MySQL Database
## ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/leave_management?createDatabaseIfNotExist=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=0000


spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:leave_management}
        username: ${DATABASE_USER:root}
        password: ${DATABASE_PASSWORD:0000}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: Asia/Kolkata
        flyway:
            enabled: false
            locations: classpath:db/migration

    server:
        port: ${PORT:8080}

    logging:
        level:
            org.springframework: INFO
            com.yourcompany.leavemanagement: DEBUG
## ===============================
## JPA / Hibernate
## ===============================
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## ===============================
## Flyway (DB Migration)
## ===============================
#spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration
#
## ===============================
## Timezone Handling
## ===============================
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#
## ===============================
## Logging
## ===============================
#logging.level.org.springframework=INFO
#logging.level.com.yourcompany.leavemanagement=DEBUG
